INSERT INTO rtguinanao.service VALUES (1,'Immunizations','COVID-19 immunization','Dose 1');
INSERT INTO rtguinanao.service VALUES (2,'Immunizations','COVID-19 immunization','Dose 2');
INSERT INTO rtguinanao.service VALUES (3,'Immunizations','COVID-19 immunization','Dose 3');
INSERT INTO rtguinanao.service VALUES (4,'Immunizations','COVID-19 immunization','Dose 4');
INSERT INTO rtguinanao.service VALUES (5,'General Medicine','Broken bone','NULL');
INSERT INTO rtguinanao.service VALUES (6,'General Medicine','Traumatic brain injury','NULL');
INSERT INTO rtguinanao.service VALUES (7,'Immunizations','Influenza immunization','NULL');
INSERT INTO rtguinanao.service VALUES (8,'General Medicine','Laceration','NULL');
INSERT INTO rtguinanao.service VALUES (9,'Laboratory and Testing','Bacterial or viral infection','NULL');
INSERT INTO rtguinanao.service VALUES (10,'Laboratory and Testing','STD testing','NULL');
INSERT INTO rtguinanao.service VALUES (11,'CAPS','ADHD','NULL');
INSERT INTO rtguinanao.service VALUES (12,'CAPS','Depression/anxiety','NULL');
